Made 'npm run build' run in strict mode
evidence-dev/template pull request #75
Opened 2023-07-11 19:50 UTC by ud3sh

2023-07-11 20:00 UTC, archiewood requested changes

2023-07-11 20:04 UTC, ud3sh commented on package.json
> +    "build:nostrict": "evidence build",
I like `permissive`.  I'll think of some examples

2023-07-17 14:57 UTC, archiewood commented on package.json
> +    "build:nostrict": "evidence build",
yeah me too

2023-12-21 21:52 UTC, archiewood commented
feels like we should merge this

2024-02-01 20:58 UTC, closed without merging