[next] Update README
evidence-dev/template pull request #78
Opened 2023-08-07 15:27 UTC by ItsMeBrianD

2023-08-07 20:33 UTC, mcrascal commented on README.md
> +### Updating:
Updating the pre-release

2023-08-07 20:34 UTC, mcrascal commented on README.md
> +The prerelease releases frequently, to ensure you have the most up-to-date changes; run `npm upgrade`.
I think this should be npm update, not upgrade

2023-08-07 20:36 UTC, mcrascal requested changes

2023-08-07 20:36 UTC, mcrascal commented on README.md
> +##### `.env`/Environment Variables
just environment variables

2023-08-07 20:36 UTC, mcrascal commented on README.md
> +
section needs a fully worked example of at least one data source. what's the connection directory, what's in the yaml, what's in the .env file.

2023-08-07 20:36 UTC, mcrascal commented on README.md
> +         1. Note that you should use [environment variables](#envenvironment-variables) for configuration that is secret (e.g. passwords), otherwise you risk checking your secrets into version contro
spelling on environment in the link

2023-08-14 02:58 UTC, ItsMeBrianD commented on README.md
> +The prerelease releases frequently, to ensure you have the most up-to-date changes; run `npm upgrade`.
```suggestion
The prerelease releases frequently, to ensure you have the most up-to-date changes; run `npm update`.
```

2023-08-14 02:58 UTC, ItsMeBrianD commented on README.md
> +##### `.env`/Environment Variables
```suggestion
##### Environment Variables
```

2023-08-14 02:59 UTC, ItsMeBrianD commented on README.md
> +         1. Note that you should use [environment variables](#envenvironment-variables) for configuration that is secret (e.g. passwords), otherwise you risk checking your secrets into version contro
Was set that way to account for the `.env/` portion; updating because that was removed

```suggestion
         1. Note that you should use [environment variables](#environment-variables) for configuration that is secret (e.g. passwords), otherwise you risk checking your secrets into version control.
```

2023-12-21 17:37 UTC, closed without merging